# Generated by Django 4.1.5 on 2023-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALÁXIA', 'Galáxia'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta')], default='', max_length=150),
        ),
    ]
